apiVersion: v1 kind: Namespace
metadata:
 name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: example
 name: flask-app-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: flask
 minReadySeconds: 20
 template:
  metadata:
   labels:
    app: flask
  spec:
   containers:
   - name: flask-app
    image: sainivikas/blog-example-flask
    command: ["flask", "run", "-h", "0.0.0.0", "-p", "80"]
---
apiVersion: v1
kind: Service
metadata:
 namespace: example
 name: flask-app-service
spec:
 selector:
  app: flask
 ports:
 - name: port-80
  protocol: TCP
  port: 80
  targetPort: 80
 type: ClusterIP
